language: c

install:
  - sh ./.travis.install.deps.sh
  - curl www.rust-lang.org/rustup.sh | sudo CFG_DISABLE_CARGO=1 bash

script:
  - ./configure
  - make
  - make test -j4
  - make install DESTDIR=${PWD}/destdir

env:
  - BITS=32
  - BITS=64

os:
  - linux
  - osx
